name: Tokens

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm ci
    - run: npm run token-transform
    - name: Archive token-transform results
      uses: actions/upload-artifact@v2
      with:
        name: transformed-tokens
        path: src/data/tokens.json
    - uses: actions/download-artifact@v2
      with:
        path: src/data
